1. Crear un vector con valores dentro del rango 10 a 49.

In [3]:
import numpy as np

In [4]:
vector1 = np.arange(50)
vector1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

2. Invertir el vector creado en el ejercicio 1.

In [5]:
vector2 = vector1[::-1]
vector2

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [ ]:
#metodo flip que es como reverse en python

3. Crear una matriz de 3x3 con los valores de 0 a 8.


In [6]:
matriz1 = np.array([[0,1,2],[3,4,5],[6,7,8]])
matriz1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
#metodo reshape 3,3

4. Encontrar los índices que no son ceros del arreglo [1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0].


In [7]:
vector4 = np.array([1,2,4,2,4,0,1,0,0,0,12,4,5,6,7,0])

for i in vector4:
  if i != 0:
    print(i)

1
2
4
2
4
1
12
4
5
6
7


In [8]:
np.where(vector4 != 0)

(array([ 0,  1,  2,  3,  4,  6, 10, 11, 12, 13, 14], dtype=int64),)

In [ ]:
#tb puede ser con el metodo np.argwhere() y np.nonzero()

5. Crear una matriz identidad de 6x6.

In [9]:
identidad5 = np.identity(6)
identidad5

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [10]:
identidad5 = np.eye(6)
identidad5

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

6. Encontrar los índices de los valores mínimos y máximos de la matriz creada en
el ejercicio 3.

In [12]:
matriz6 = matriz1

print(matriz6)

Min = matriz6.min()
Max = matriz6.max()

print(Min)
print(Max)

resultmin = np.where(matriz6 == Min)
resultmax = np.where(matriz6 == Max)

print(resultmin)
print(resultmax)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
0
8
(array([0], dtype=int64), array([0], dtype=int64))
(array([2], dtype=int64), array([2], dtype=int64))


7. Crear una matriz de 10x10 con 1 en los bordes y 0 en el interior (con rangos de índices).

In [20]:
matriz7 = np.zeros((10,10))

matriz7[0:1] = 1

matriz7[:, 0] = 1

matriz7

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
matriz7 = np.ones((10,10))

matriz7 = [1:-1, 1:-1] = 0

SyntaxError: invalid syntax (Temp/ipykernel_12708/1536090325.py, line 3)

8. Crear una matriz de 5x5 con valores en los renglones que vayan de 0 a 4.

In [27]:
matriz0 = np.zeros((5,5))

matriz8 = np.array([0,1,2,3,4])

matriz8 = matriz0 + matriz8

matriz8


array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [17]:
matrizx = np.tile(np.arange((0,5),5).reshape(5,5))

TypeError: unsupported operand type(s) for -: 'int' and 'tuple'

9. Crear dos arreglos al azar A y B, verificar si son iguales.

In [42]:
arregloA = np.random.rand(3,2)
arregloB = np.random.rand(3,2)

if arregloA.all == arregloB.all:
    print('son iguales')
else:
    print('no lo son')



no lo son


In [ ]:
#método equal

10.Crear una matriz de 20x20 de valores aleatorios entre 1 y 100, luego indicar su media, su mediana, su moda y el desvío estándar. Los valores que den como resultado flotantes deben tener como máximo 2 decimales.

In [62]:
matriz10 = np.random.randint(low=1, high=101, size=(20,20), dtype=int)

media = round(np.mean(matriz10),2)

mediana = round(np.median(matriz10),2)

import statistics as stat

moda = matriz10.flatten()

moda = round(stat.mode(moda),2)

std = round(np.std(matriz10),2)


print(f'la media es {media}')
print(f'la mediana es {mediana}')
print(f'la moda es {moda}')
print(f'la ds es {std}')

la media es 55.01
la mediana es 56.0
la moda es 25
la ds es 28.56


11.Crear dos arreglos de 4 elementos enteros y hacer las siguientes operaciones: sumarlos, restarle el segundo al primero, multiplicarlos, dividir el primero por el segundo. Hacerlo utilizando métodos.

In [68]:
arreglo1 = np.array([[1,2],[3,4]])
arreglo2 = np.array([[4,5],[6,7]])

suma = np.add(arreglo1, arreglo2)
resta = np.subtract(arreglo2, arreglo1)
mul = np.multiply(arreglo1, arreglo2)
div = np.divide(arreglo1, arreglo2)

print(suma)
print(resta)
print(mul)
print(div)

[[ 5  7]
 [ 9 11]]
[[3 3]
 [3 3]]
[[ 4 10]
 [18 28]]
[[0.25       0.4       ]
 [0.5        0.57142857]]


12.Crear una matriz de 4x4 de valores aleatorios entre 1 y 10, y luego agregarle una fila de 0s al final.+

In [75]:
matriz12 = np.random.randint(low=1, high=11, size=(4,4), dtype=int)

print(matriz12)

fila = np.array([0,0,0,0])

matriz12 = np.append(matriz12,[fila],axis= 0)

matriz12

[[ 6  6  2  4]
 [ 9  2  4  1]
 [ 3  5 10  7]
 [ 1  9  7  4]]


array([[ 6,  6,  2,  4],
       [ 9,  2,  4,  1],
       [ 3,  5, 10,  7],
       [ 1,  9,  7,  4],
       [ 0,  0,  0,  0]])

In [ ]:
# metodo np.vstak

13.Crear dos arreglos de 6 elementos de valores aleatorios entre 0 y 1 y luego realizar las operaciones lógicas and y or con los métodos de NumPy.

In [20]:
matriz13a = np.random.randint(low=0, high=1, size=(1,6), dtype=int)

matriz13b = np.random.randint(low=0, high=2, size=(1,6), dtype=int)

And = np.logical_and(matriz13a, matriz13b)
Or = np.logical_or(matriz13a, matriz13b)

print(matriz13a)
print(matriz13b)

print(And)
print(Or)

[[0 0 0 0 0 0]]
[[0 1 0 0 1 1]]
[[False False False False False False]]
[[False  True False False  True  True]]


14.Crear un arreglo de 4 elementos de entre 0 y 10, informar la cantidad de elementos que tiene y también cuántos bytes ocupa el arreglo.

In [22]:
matriz14 = np.random.randint(low=0, high=11, size=(1,4), dtype=int)

print(matriz14)
print(matriz14.size)
print(matriz14.nbytes)

[[7 0 1 9]]
4
16
